image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      sudo apt install -y nodejs
      bundle config set path vendor/bundle
      bundle install
      npm install
    command: bundle exec middleman server
github:
  prebuilds:
    addCheck: false
