image: gitpod/workspace-full
tasks:
  - init: |
      bundle config set path vendor/bundle
      bundle install
      npm install
    command: bundle exec middleman server
github:
  prebuilds:
    addCheck: false
