inherit_mode:
  merge:
    - Exclude

AllCops:
  DisabledByDefault: true
  Exclude:
    - "bin/*"

Layout/ArgumentAlignment:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never
