language: ruby
cache: bundler
rvm:
  - 3.0.0
install:
  - gem install bundler:2.2.11
  - bundle config set --local deployment true
  - bundle install
  - eval "$(ssh-agent -s)"
script:
  - |
      if [ "$TRAVIS_BRANCH" = "master" ];
      then bundle exec rake ci:deploy
      fi
branches:
  only:
    - master
    - staging
    - trying
