name: Middleman deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true # 'bundle install' and cache

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        run: |
          eval "$(ssh-agent -s)"
          bundle exec rake ci:deploy
        env:
          encrypted_key: ${{ secrets.encrypted_key }}
          encrypted_iv: ${{ secrets.encrypted_iv }}
          COMMIT_AUTHOR_EMAIL: team@bundler.io
